# Generated by Django 4.1.7 on 2023-03-26 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0005_image_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='up_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 16, 22, 38, 737758)),
        ),
    ]
