# Generated by Django 4.1.7 on 2023-03-26 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0006_image_image_id_alter_image_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='up_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 16, 24, 20, 495383)),
        ),
    ]
