# Generated by Django 4.1.7 on 2023-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0007_alter_image_image_id_alter_image_up_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='up_time',
        ),
        migrations.AddField(
            model_name='image',
            name='image_class',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
